feat/LIST-33-functionality-sortBy
HackYourFuture-CPH/CINEMANIA pull request #107
Opened 2023-05-17 15:39 UTC by agkabir

# Description
Functionality for different sortBy options like ‘price', ‘rating’, and 'recently added'  have been implemented. By using this functionality a user can view sorted results of movies according to the option he/selects from the Sort by Select box. 

# Jira task link
https://hackyourfuture-dk.atlassian.net/browse/LIST-33

# Screenshots (if applicable)

2023-05-17 16:02 UTC, shobanamg commented on packages/client/src/components/Categories/CategoriesAndSearchBarAndSortBy.jsx
> +  const handleOnClick = (catId) => {
just try to name it better, and include the category in the function name, so that it gives more clarity

2023-05-17 16:11 UTC, shobanamg commented
First of all, there is no need for a single context for both movies and categories. I understand your idea. But do we really need to couple it with movie context tightly?  In my opinion, the categories component is a simple one that can have its own state and it does not need context or reducer. 

With this implementation, we are complicating the reusability of the category component
@shpomp, @timnoorlander, Please let me your opinion on this.

2023-05-18 11:27 UTC, shpomp requested changes
A lot of good work was done here and the code, apart from some naming and structuring is very clean and clear. 🤩 
You can definitely use some parts after some restructuring and refactoring 👍🏽  ⭐ 
Please also make sure to share with the team and tell them more about the reducer if they have not used it before 🙏🏽

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/components/Categories/CategoriesAndSearchBarAndSortBy.jsx
> +export const CategoriesAndSearchBarAndSortBy = () => {
This is like showing the middle finger to React 😅 
It is not a good practice to plop so many things together and then have to have such long combined naming. 

You might, however, sometimes see components that are made with the purpose of combining several components together. It is possible, but then you would have a certain indicative name for it and that component should normally not have any functionality.

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/components/Categories/CategoriesAndSearchBarAndSortBy.jsx
> +      sx={{
On Sunday, we talked extensively about style approach optimization, but here I still see quite a few `sx` overrides with a lot of the same properties. 
Try to revisit the styling question in the team and see what approach you can take. 
You can take inspiration from the Landing team that chose a strategy and is sticking to it quite well. 👍🏽

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/components/MovieList/MovieList.jsx
> +      )}
This is a very nice and essential check! 👍🏽

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/containers/MovieListPage/ReducerForFetchMoviesAndCategories.jsx
> +  let URI = `${apiURL()}/movies?`;
This is very nicely done and structured, very clean and clear. 
It makes it very easy for anybody to see all the possible movie fetches that can happen and makes it easy to work with this 👏🏽

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/containers/MovieListPage/ReducerForFetchMoviesAndCategories.jsx
> +  switch (action.type) {
As we discussed, a reducer as such is not a bad idea at all. 
However, as we agreed, if we need context and reducer for both movies and categories, then they should be separated. However, I do not see why categories context would be necessary, but you can try to prove that it is! :)

2023-05-18 11:27 UTC, shpomp commented on packages/client/src/context/FetchCategoriesAndMovies.jsx
> +  const [state, dispatch] = useReducer(
Once again, should be separated if we even need both, and the naming of the context should be
SomethingContext. 
Saying fetchSomethingSomething makes it sound like a helper or a hook and it is not intuitive for an outsider 🙏🏽

2023-05-18 14:14 UTC, closed without merging