FE-adjust design for featuredMovies according to 1440px
HackYourFuture-CPH/CINEMANIA pull request #112
Opened 2023-05-17 23:55 UTC by na-talia

# Description

Adjusting the size of elements according to the screen resolution of 1440 px.
Removing Section Placeholder in the featuredMovie component.

# Jira task link

https://hackyourfuture-dk.atlassian.net/jira/software/projects/LANDING/boards/6?selectedIssue=LANDING-66

# Screenshots (if applicable)

2023-05-18 07:16 UTC, jawkha commented
@na-talia Everything looks good. There is, however, a typo here:
https://github.com/HackYourFuture-CPH/CINEMANIA/blob/0a68c82d93aaed0399db210b8cd6667dd4945a76/packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx#L84
When you fix that, it will be ready to merge.

2023-05-18 07:20 UTC, jawkha requested changes
Please correct the typo here:
https://github.com/HackYourFuture-CPH/CINEMANIA/blob/0a68c82d93aaed0399db210b8cd6667dd4945a76/packages/client/src/components/FeaturedMovie/FeaturedMovie.jsx#L84

2023-05-18 21:02 UTC, shpomp approved these changes

2023-05-19 07:28 UTC, jawkha approved these changes

2023-05-19 14:20 UTC, merged