Fix/FE adjust most popular movies component according to design 1440px  and link to movies details
HackYourFuture-CPH/CINEMANIA pull request #113
Opened 2023-05-18 01:12 UTC by Kositthai

# Description

- Adjust most popular movies component according to design 1440px 
- Link most popular element to movies/id when click on it 

- Edited return error to Throw error in MostPopular file 

# Jira task link
https://hackyourfuture-dk.atlassian.net/jira/software/projects/LANDING/boards/6?selectedIssue=LANDING-69
https://hackyourfuture-dk.atlassian.net/jira/software/projects/LANDING/boards/6?selectedIssue=LANDING-58

# Screenshots (if applicable)

https://github.com/HackYourFuture-CPH/CINEMANIA/assets/94117213/aac7c637-5a5a-4443-a121-a4ce05832b1f

2023-05-18 07:55 UTC, jawkha requested changes
Other than the two minor issues, it all looks quite good.
Really good work!!

2023-05-18 07:55 UTC, jawkha commented on packages/client/src/containers/CarouselWrapper/MostPopular.jsx
>          setPopularMovies(data.slice(1, 12));
@Kositthai Can you please confirm the structure of the `data` object here? I am getting an error here.

2023-05-18 07:55 UTC, jawkha commented on packages/client/src/containers/CarouselWrapper/MostPopular.jsx
@Kositthai It looks like the name of the component has a typo. Can you please also take a look at it?

2023-05-18 15:03 UTC, Kositthai commented
> Other than the two minor issues, it all looks quite good. Really good work!!

Thank you so much for your review! I have fixed my code as your suggestion :) 
Kindly let me now if I need to change anything else otherwise kindly approve

2023-05-19 07:27 UTC, jawkha approved these changes
Seems to be working now. Good work!!

2023-05-19 10:07 UTC, Kositthai commented
> Seems to be working now. Good work!!

Thank you so much!

2023-05-19 10:08 UTC, merged