feat/view-25 - Simple rating component + movies/:id route
HackYourFuture-CPH/CINEMANIA pull request #14
Opened 2023-05-07 21:26 UTC by Cygap

# Description: added route movies/:id to app.js (allows to test frontend components without modifying app.js further, added empty MovieView component to contain all the frontend of the View page, added simple rating component from MUI

# Jira task link: https://hackyourfuture-dk.atlassian.net/browse/VIEW-25

# Screenshots (if applicable) 
![image](https://user-images.githubusercontent.com/113382267/236703313-1e3a8ffc-05df-4b42-aa64-a068e8f33c3f.png)

2023-05-07 21:51 UTC, shpomp requested changes
No package updates in PRs, unless coordinated and agreed 🙏🏽

2023-05-08 07:14 UTC, Cygap commented
Sorry for that. These were traces of me fixing a problem with linters... Now everything should be ok. Can you please check?

2023-05-08 15:52 UTC, shpomp requested changes
By all means looks good - nice and simple! ⭐ 

However, it is not finished and final as per the design, and neither Jira not PR description indicates that more work will happen on it as the next step.

2023-05-08 20:27 UTC, Cygap commented on packages/client/src/App.js
> +          {/* Added movies/:id path to be able to test frontend components for the Movie View page */}
Removed comments... and also added more reasonable description to Jira task

2023-05-08 21:32 UTC, shpomp commented
There is a lot of confusion here still. 🥺 

The user story title is unclear. 
The user story description that this task is under now is "As a developer, I want to see the reviews of the movies in the database". So this task is unrelated to the story and should not be there. 
There is another task that is also unrelated to the story.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/64137994/236939323-5573a885-d621-4805-b2bd-b85ad06ae518.png">

When the task gets to where it needs to be, the Jira tasks situation should reflect the totality of the user story. 
The end result of the story being fulfilled is the right design of the rating component - which should be a task in itself, that could even be already linked here showing that the styling is not final, but will be finalized in this sprint. 
In that way, anybody looking at it would know that this is not final and there is a task planned in this sprint to come back and adjust the styles. 

@Cygap 
and @Aditi-Sawardekar  as the Agile Agent ⭐

2023-05-10 08:58 UTC, merged

2023-05-10 08:58 UTC, Cygap commented
We have moved it to a more appropriate place in Jira already, removed comments