add endpoint to retrieve movies with the same category
HackYourFuture-CPH/CINEMANIA pull request #20
Opened 2023-05-08 12:26 UTC by aladdin91

…imilar movies section

# Description
add endpoint to retrieve movies with the same category to show them in the similar movies section 

# Jira task link
https://hackyourfuture-dk.atlassian.net/browse/VIEW-28

# Screenshots (if applicable)

2023-05-08 15:44 UTC, shpomp commented
Looks good to me! But asked a Backend pro mentor to review 🙏🏽

2023-05-09 06:06 UTC, itsgauravsaxena requested changes
A small comment about status code. Rest looks good

2023-05-09 12:36 UTC, aladdin91 commented on packages/server/api/controllers/movies.controller.js
> +      .limit(9);
Because we will show similar moves in Carousel that show 3 movies at a time

2023-05-09 12:36 UTC, aladdin91 commented on packages/server/api/controllers/movies.controller.js
> +      return { message: `No movies found under this category` };
done ✅

2023-05-10 06:19 UTC, itsgauravsaxena approved these changes
Looks good

2023-05-10 20:14 UTC, aladdin91 commented
thanks for the review 🙏 , i will merge it now 😊

2023-05-10 20:14 UTC, merged